default: &default
  pool: 25
  timeout: 5000

production:
  <<: *default
  adapter: <%= SECRET["DATABASE"]["PROD_ENGINE"] %>
  host: <%= SECRET["DATABASE"]["PROD_HOST"] %>
  database: twenty_four_seven
  username: <%= SECRET["DATABASE"]["PROD_UN"] %>
  password: <%= SECRET["DATABASE"]["PROD_PW"] %>
  port: <%= SECRET["DATABASE"]["PROD_PORT"] %>

staging:
  <<: *default
  adapter: <%= SECRET["DATABASE"]["PROD_ENGINE"] %>
  host: <%= SECRET["DATABASE"]["PROD_HOST"] %>
  database: twenty_four_seven
  username: <%= SECRET["DATABASE"]["PROD_UN"] %>
  password: <%= SECRET["DATABASE"]["PROD_PW"] %>
  port: <%= SECRET["DATABASE"]["PROD_PORT"] %>
  
# development:
#   <<: *default
#   adapter: <%= SECRET["DATABASE"]["PROD_ENGINE"] %>
#   host: <%= SECRET["DATABASE"]["PROD_HOST"] %>
#   database: twenty_four_seven
#   username: <%= SECRET["DATABASE"]["PROD_UN"] %>
#   password: <%= SECRET["DATABASE"]["PROD_PW"] %>
#   port: <%= SECRET["DATABASE"]["PROD_PORT"] %>

development:
  <<: *default
  adapter: <%= SECRET["DATABASE"]["DEV_ENGINE"] %>
  host: <%= SECRET["DATABASE"]["DEV_HOST"] %>
  database: <%= SECRET["DATABASE"]["DEV_DB"] %>
  username: satoshy
  password: 18satoshy

# production:
#   <<: *default
#   adapter: <%= SECRET["DATABASE"]["DEV_ENGINE"] %>
#   host: <%= SECRET["DATABASE"]["DEV_HOST"] %>
#   database: <%= SECRET["DATABASE"]["DEV_DB"] %>